services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true